version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root  # Set the root password
      MYSQL_DATABASE: jobs       # Optional: Create a default database
      MYSQL_USER: admin                # Optional: Create a default user
      MYSQL_PASSWORD: admin        # Optional: Set the user's password
    ports:
      - "3306:3306"                     # Map MySQL port to the host
    volumes:
      - mysql_data:/var/lib/mysql       # Persist MySQL data
volumes:
  mysql_data:

